### ISSUE TITLE
ClassNotFoundException after enabled the proguard in my app

### ISSUE THREAD

**Issue by siliconprime-van** [plaid/plaid-link-android#100]
at the Runtime when I call function Plaid.initialize(application);
the app crash with logs below:
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.plaid.link.Plaid" on path: DexPathList[[zip file "/data/app/com.base.integratedapp-pF50x8bSTzPAGIBdj-891g==/base.apk"],nativeLibraryDirectories=[/data/app/com.base.integratedapp-pF50x8bSTzPAGIBdj-891g==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.grand.sdk.GrandSDK.initSKDK(SourceFile:34) 
        at com.base.integratedapp.AppAplication.onCreate(AppAplication.java:13) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6488) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:226) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1884) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7386) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 

I had added:
-keep class com.plaid.link.Plaid{ *; }
-keep class com.plaid.link** { *; }
to proguard-reles.pro but it not helpful

**Comment by siliconprime-van** [comment]
I have added
-keep class com.plaid.link.** { *; }
 to proguard.pro: but it not helpful, still got same error above

**Comment by DrGreyManAfreeMASONG7** [comment]
Thank you all very much... I apologise, I'm the new guy. Hey

**Comment by JeroenMols** [comment]
Hi @siliconprime-van,

Can you provide us a bit more information with regards to your issue?

- What version of our SDK are you using?
- What code snippet are you using to open our Link?

We've recently deprecated `Plaid.initialize(application)` and hence that class is no longer accessible.
See our full migration guide: https://plaid.com/docs/link/android/android-v3-migration/

Jeroen

**Comment by JeroenMols** [comment]
Hi @siliconprime-van ,

Is there anything else we could do to help you with this issue?

**Comment by JeroenMols** [comment]
Hi @siliconprime-van ,

We haven't heard back from you in a while. Hence we're assuming this issue is no longer relevant and are closing it at this point. Feel free to reopen or a file a new issue should this assessment be incorrect.

Many thanks for taking the time and filing this!
