### ISSUE TITLE
Crash on launching the app after upgrading from 2.2.0 to 3.0.1

### ISSUE THREAD

**Issue by mrunal-upadhyay** [plaid/plaid-link-android#102]
This issue is caused on debug build. Crash occurs on launching the app
Below is the snippet of crash logs from logcat:

2020-10-13 16:54:37.303 27186-27245/ E/AndroidRuntime: FATAL EXCEPTION: pool-11-thread-1
    Process: , PID: 27186
    java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
        at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:507)
        at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
        at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:93)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:107)
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
        at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:395)
        at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:403)
        at com.google.firebase.perf.v1.ApplicationInfo$Builder.setAndroidAppInfo(ApplicationInfo.java:934)
        at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.syncInit(FirebasePerfClearcutLogger.java:278)
        at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.access$000(FirebasePerfClearcutLogger.java:62)
        at com.google.firebase.perf.internal.FirebasePerfClearcutLogger$1.run(FirebasePerfClearcutLogger.java:169)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

Could it be because of firebase libraries causing an issue with Plaid? Let us know if you have any insights around this?

Just to add more information:
I could reproduce the issue by using firebase_performance = "19.0.9" dependency

App works fine with firebase_performance = "19.0.8" version

This issue seems to be caused after upgrading firebase_performance library from 19.0.8 to 19.0.9

**Comment by DrGreyManAfreeMASONG7** [comment]
Thank you

**Comment by JeroenMols** [comment]
I can't seem to find a difference in dependencies on `protobuf` between `firebase-perf:19.0.8` and `firebase-perf:19.0.9`

```
+--- com.google.firebase:firebase-perf:19.0.8
|    +--- com.google.firebase:firebase-config:19.2.0
|    |    +--- com.google.firebase:firebase-abt:19.1.0
|    |    |    \--- com.google.protobuf:protobuf-javalite:3.11.0
```

```
+--- com.google.firebase:firebase-perf:19.0.9
|    +--- com.google.firebase:firebase-config:19.2.0
|    |    +--- com.google.firebase:firebase-abt:19.1.0
|    |    |    \--- com.google.protobuf:protobuf-javalite:3.11.0
```

But our SDK transistively bumps that version to `3.13.0`

```
+--- com.plaid.link:sdk-core:3.0.1
|    +--- com.google.protobuf:protobuf-javalite:3.13.0
```

So this might be a runtime incompatibility between `firebase-perf:19.0.9` and the newer `protobuf-javalite:3.13.0`.

Can you please try to add the following to your top level `build.gradle` file:

```
allprojects {
    configurations.all {
        resolutionStrategy {
            force 'com.google.protobuf:protobuf-javalite:3.11.0'
        }
    }
}
```

Does that fix your issue?

**Comment by mrunal-upadhyay** [comment]
Thank You. This change fixes the issue.

**Comment by JeroenMols** [comment]
Thank you for testing and letting us know it resolved your issue. 

We've addressed this issue and it will you can expect a fix this in the next release of our SDK (~mid November).

For the time being you have two options:

- Stay on `firebase-perf:19.0.8`
- force the dependency to `3.11.0`
