### ISSUE TITLE
Redirect Uris android

### ISSUE THREAD

**Issue by AanalShah** [plaid/plaid-link-android#13]
i configure with "myapp://plaid-redirect" uri but got crash while finishing process 

Process: com.tekxlab.purocredit, PID: 2830
    android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=myapp://plaid-redirect flg=0x10000000 }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2022)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1679)
        at android.app.Activity.startActivityForResult(Activity.java:4651)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:4609)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at android.app.Activity.startActivity(Activity.java:4970)
        at android.app.Activity.startActivity(Activity.java:4938)
        at com.plaid.linkwebview.BasePlaidWebViewClient.openWebsite(WebViewClients.kt:43)
        at com.plaid.linkwebview.PlaidWebClient.shouldOverrideUrlLoading(WebViewClients.kt:71)
        at IG0.a(PG:1)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:15)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:165)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by keyurbelani** [comment]
@AanalShah.

You have to register same uri with Plaid dashboard and AndroidManifest.xml also.

**1. To register redirect uri on Plaid Dashboard:**

1. Log into your Plaid Dashboard
2. Select API under Team Settings in the top navigation bar
3. Click configure then Add New Uri then enter your Uri (for example "myapp://plaid-redirect")
4. Click Save Changes

**2. Register redirect uri in AndroidManifest.xml:**

```
<activity android:name="com.plaid.link.redirect.LinkRedirectActivity">
            <intent-filter android:autoVerify="true">
                <action android:name="android.intent.action.VIEW" />

                <category android:name="android.intent.category.DEFAULT" />
                <category android:name="android.intent.category.BROWSABLE" />

                <data
                    android:host="plaid-redirect"
                    android:scheme="simplypay" />
            </intent-filter>
        </activity>
```

**3. Pass same uri with LinkConfiguration**

```
LinkConfiguration(
                        // required
                        clientName = "SimplyPay App",
                        products = listOf(PlaidProduct.TRANSACTIONS),
                        webviewRedirectUri = "simplypay://plaid-redirect",)
```

@AanalShah Please apply above 3 points with your project and check and let me know.

**Comment by AanalShah** [comment]
@keyurbelani  i did the same now i not got crash but after tab on continue button screen freeze not calling onActivityResult()
