### ISSUE TITLE
java.lang.NoSuchFieldError: No field Companion of type Lokhttp3/HttpUrl$Companion

### ISSUE THREAD

**Issue by antonPolosin** [plaid/plaid-link-android#132]
Integrating PLAID Android SDK to an existing project, when opening link app crashes after couple of seconds. This is the error from the logcat
```
 java.lang.NoSuchFieldError: No field Companion of type Lokhttp3/HttpUrl$Companion; in class Lokhttp3/HttpUrl; or its superclasses (declaration of 'okhttp3.HttpUrl' appears in /data/app/test.app==/base.apk!classes5.dex)
        at com.plaid.internal.fm0.b(SourceFile:1)
        at com.plaid.internal.fm0.a(SourceFile:6)
        at com.plaid.internal.yg0.a(SourceFile:1)
        at com.plaid.internal.lm0.shouldOverrideUrlLoading(SourceFile:2)
        at tY.a(PG:3)
        at xl.b(PG:81)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:172)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by antonPolosin** [comment]
Solved the problem by updating okhttp to the latest version

**Comment by JeroenMols** [comment]
Interesting, thanks for letting us know!

Could you please share what version of Okhttp you were using and what version you've upgraded to?
There might still be something we could do/document to help here.

**Comment by antonPolosin** [comment]
I think in android plaid integration docs just include that if project uses okhttp3, it's required to be version 4 or the latest one.
