### ISSUE TITLE
Sila - Error code INVALID_FIELD and ERROR Message Android package name must be configured in the developer dashboard. 

### ISSUE THREAD

**Issue by georgeinigo** [plaid/plaid-link-android#135]
Hey There! I ran the example project for Android plaid link and it worked fine on my Android emulator. However when I tried to integrate the code into my own project I received the error code INVALID_FIELD after calling Plaid.openLink(). I didn't change any part of the code, except for the name of the files and clientName. I'm using this for Sila. So applied Sila public key.

Should I add my app package name to Plaid dashboard. Sila mentioned that no need to create an account with plaid. Assist me further. I tried with 1.4.1 and 2.0.0 dependency in my gradle. Assist me further. Thanks in advance.

I got the below errors while run the app

2021-02-08 15:47:49.211 4070-4070/com.payr.customer E/j3$d: java.lang.IllegalStateException: 
        at com.plaid.j3$h.accept(SourceFile:21)
        at io.reactivex.internal.operators.single.SingleDoOnEvent$DoOnEvent.onSuccess(SingleDoOnEvent.java:55)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

**Comment by amytang0** [comment]
Hey, sounds like you'll need to add your example project's package name to the developer dashboard. It sounds like Sila already has a test app package name configured on their dashboard, so another solution would be to change your example project's package name to match.

**Comment by JeroenMols** [comment]
Warm reminder, has Amy's suggestion worked for you?

**Comment by amytang0** [comment]
Closing due to >30 days of inactivity
