### ISSUE TITLE
Receiving a bunch of errors in the Plaid Link WebView, and unable to login with the generic Sandbox account

### ISSUE THREAD

**Issue by shalbert94** [plaid/plaid-link-android#137]
# The problem

There are seemingly two issues: 
- A bunch of errors coming from the Plaid Link flow, though the pages seem to load correctly
- Logging in with user_good/pass_good in the Sandbox environment is not working, resulting in the "Invalid Credentials" screen displaying.

I don't know if these errors are linked. If they aren't, this issue can be split into two.

# Environment

|                        |  |
| ------------------------| ---------- |
| Android OS Version                    | API 30            |
| Android Devices/Emulators    | Pixel 4 emulator                |

# Steps to Reproduce

If necessary, describe the problem you have been experiencing in more detail.
Please include the configuration you are using for Link (exluding your keys
and personally identifiable information)

Steps to reproduce errors:
1. Launch Plaid link (link details below)
2. Go through flow towards entering credentials
Expected: No `LinkHttpErrorException` is logged
Actual: Several `LinkHttpErrorException`s are logged

Steps to reproduce invalid credentials:
1. Launch Plaid link (link details below)
2. Go through flow towards entering credentials
3. Select any institution
4. Enter user_good/pass_good credentials
Expected: Login is successful
Actual: An Invalid Credentials error screen displays

To create the Link Token, the following values are probably valuable to share:
**Plaid Client state**
```
{
  client_id: "<client ID>",
  secret: "<sandbox secret>",
  env: "https://sandbox.plaid.com",
  client_request_opts: {
    version: "2020-09-14",
  },
}
```

**CreateLinkTokenOptions**
```
{
  access_token: undefined,
  account_filters: undefined,
  android_package_name: "<android package>",
  client_name: "<name>",
  country_codes: [
    "CA",
    "US",
  ],
  language: "en",
  link_customization_name: "default",
  products: [
    "transactions",
  ],
  user: {
    client_user_id: "<User ID>",
  },
  webhook: "<webhook URL>",
}
```

# Logs
```
2021-03-17 06:19:05.445 W: onReceivedError
    com.plaid.link.exception.LinkHttpErrorException: WebResourceError { Error Code: -1 ; Description: There was a network error. }
        at com.plaid.internal.vu0.onReceivedError(SourceFile:6)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410681:133)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-17 06:19:05.448 W: onReceivedHttpError
    com.plaid.link.exception.LinkHttpErrorException: WebResourceResponse{, MimeType='', Encoding='', StatusCode=404, ReasonPhrase='Not Found', ResponseHeaders={Client-Via=shouldInterceptRequest}, data=null}
        at com.plaid.internal.su0.onReceivedHttpError(SourceFile:9)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410681:87)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-17 06:19:05.462 W: onReceivedError
    com.plaid.link.exception.LinkHttpErrorException: WebResourceError { Error Code: -1 ; Description: There was a network error. }
        at com.plaid.internal.vu0.onReceivedError(SourceFile:6)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410681:133)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-17 06:19:05.507 W: onReceivedError
    com.plaid.link.exception.LinkHttpErrorException: WebResourceError { Error Code: -1 ; Description: There was a network error. }
        at com.plaid.internal.vu0.onReceivedError(SourceFile:6)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410681:133)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-17 06:19:05.508 W: onReceivedHttpError
    com.plaid.link.exception.LinkHttpErrorException: WebResourceResponse{, MimeType='', Encoding='', StatusCode=404, ReasonPhrase='Not Found', ResponseHeaders={Client-Via=shouldInterceptRequest}, data=null}
        at com.plaid.internal.su0.onReceivedHttpError(SourceFile:9)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410681:87)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-17 06:19:05.508 W: onReceivedHttpError
    com.plaid.link.exception.LinkHttpErrorException: WebResourceResponse{, MimeType='', Encoding='', StatusCode=404, ReasonPhrase='Not Found', ResponseHeaders={Client-Via=shouldInterceptRequest}, data=null}
        at com.plaid.internal.su0.onReceivedHttpError(SourceFile:9)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410681:87)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-17 06:19:42.150 D: plaidcallback plaidlink://event?error_code&error_message&error_type&event_name=TRANSITION_VIEW&exit_status&institution_search_query&link_session_id=b190a7cb-55a5-4773-95be-65b3745bf6ae&mfa_type&request_id&timestamp=2021-03-17T10%3A19%3A42.008Z&view_name=SELECT_INSTITUTION
2021-03-17 06:20:16.550 D: plaidcallback plaidlink://event?error_code&error_message&error_type&event_name=TRANSITION_VIEW&exit_status&institution_id=ins_39&institution_name=RBC%20Royal%20Bank&institution_search_query&link_session_id=b190a7cb-55a5-4773-95be-65b3745bf6ae&mfa_type&request_id&timestamp=2021-03-17T10%3A20%3A16.468Z&view_name=CREDENTIAL
2021-03-17 06:20:16.560 D: plaidcallback plaidlink://event?error_code&error_message&error_type&event_name=SELECT_INSTITUTION&exit_status&institution_id=ins_39&institution_name=RBC%20Royal%20Bank&institution_search_query&link_session_id=b190a7cb-55a5-4773-95be-65b3745bf6ae&mfa_type&request_id&timestamp=2021-03-17T10%3A20%3A16.469Z&view_name
2021-03-17 06:20:36.418 D: plaidcallback plaidlink://event?error_code&error_message&error_type&event_name=TRANSITION_VIEW&exit_status&institution_id=ins_39&institution_name=RBC%20Royal%20Bank&institution_search_query&link_session_id=b190a7cb-55a5-4773-95be-65b3745bf6ae&mfa_type&request_id&timestamp=2021-03-17T10%3A20%3A36.340Z&view_name=LOADING
2021-03-17 06:20:36.422 D: plaidcallback plaidlink://event?error_code&error_message&error_type&event_name=SUBMIT_CREDENTIALS&exit_status&institution_id=ins_39&institution_name=RBC%20Royal%20Bank&institution_search_query&link_session_id=b190a7cb-55a5-4773-95be-65b3745bf6ae&mfa_type&request_id&timestamp=2021-03-17T10%3A20%3A36.341Z&view_name
2021-03-17 06:20:42.707 W: onReceivedHttpError
    com.plaid.link.exception.LinkHttpErrorException: WebResourceResponse{, MimeType='application/json', Encoding='utf-8', StatusCode=400, ReasonPhrase='Bad Request', ResponseHeaders={Plaid-Version=2019-05-29, Server=nginx, Access-Control-Allow-Origin=https://secure.plaid.com, Access-Control-Allow-Credentials=true, Connection=keep-alive, Content-Encoding=gzip, Vary=Accept-Encoding, Origin, Content-Length=278, Date=Wed, 17 Mar 2021 10:20:43 GMT, Content-Type=application/json; charset=utf-8}, data=null}
        at com.plaid.internal.su0.onReceivedHttpError(SourceFile:7)
        at Cs.handleMessage(chromium-TrichromeWebViewGoogle.apk-stable-410410681:87)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
2021-03-17 06:20:43.952 D: plaidcallback plaidlink://event?error_code&error_message&error_type&event_name=TRANSITION_VIEW&exit_status&institution_id=ins_39&institution_name=RBC%20Royal%20Bank&institution_search_query&link_session_id=b190a7cb-55a5-4773-95be-65b3745bf6ae&mfa_type&request_id=BxVJS59bo2rb2sl&timestamp=2021-03-17T10%3A20%3A43.823Z&view_name=ERROR
2021-03-17 06:20:43.967 D: plaidcallback plaidlink://event?error_code=INVALID_CREDENTIALS&error_message=the%20provided%20credentials%20were%20not%20correct&error_type=ITEM_ERROR&event_name=ERROR&exit_status&institution_id=ins_39&institution_name=RBC%20Royal%20Bank&institution_search_query&link_session_id=b190a7cb-55a5-4773-95be-65b3745bf6ae&mfa_type&request_id=BxVJS59bo2rb2sl&timestamp=2021-03-17T10%3A20%3A43.825Z&view_name
```

**Comment by shalbert94** [comment]
The invalid credentials seem to have been resolved. There are also fewer `LinkHttpErrorException`s logged. Not sure what changed in the last two minutes, because my code didn't and the application's data wasn't even cleared between when it didn't work and when it started working.
