### ISSUE TITLE
Update crashing 3.2.4

### ISSUE THREAD

**Issue by burundis** [plaid/plaid-link-android#141]
Good morning, after updating android sdk from version 2.2.0 to 3.2.4 I am getting the following crash in production, any ideas? Thank you. 

java.lang.IllegalStateException: Fragment CustomFragment{dc20974} (523229fe-f006-43be-9e19-14fec6cf7f05)} not attached to a context.
    at androidx.fragment.app.Fragment.requireContext(Fragment.java:898)
    at com.plaid.link.Plaid.openLinkInternal(SourceFile:4)
    at com.plaid.link.PlaidHandler.open(SourceFile:2)
    at com.example.app.BasePlaidFragment.initPlaidHandler(BasePlaidFragment.kt:155)
    at com.example.app.BasePlaidFragment.getLinkTokenConfiguration(BasePlaidFragment.kt:160)
    at com.example.app.BasePlaidFragment.access$getLinkTokenConfiguration(BasePlaidFragment.kt:27)
    at com.example.app.BasePlaidFragment$getLinkToken$1.accept(BasePlaidFragment.kt:170)
    at com.example.app.BasePlaidFragment$getLinkToken$1.accept(BasePlaidFragment.kt:27)
    at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
    at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:214)
    at android.app.ActivityThread.main(ActivityThread.java:7711)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by kevingermainbusiness** [comment]
I'm a regular user of this API, did you try using the latest version **3.2.5** << implementation "com.plaid.link:sdk-core:3.2.5" >>

**Comment by amytang0** [comment]
Hi, it looks like your CustomFragment isn't attached to the Activity yet. Can you also post your `open` code with sensitive information redacted?

**Comment by burundis** [comment]
Thanks @kevingermainbusiness I will try with the latest version and adding what you tell me

**Comment by burundis** [comment]
@amytang0 Thanks let me see if I can extract an example from the scenario to be able to share, in debug it works fine but in release that is happening :(

**Comment by JeroenMols** [comment]
Closing this issue as it hasn't received an update in more than 30 days.
Thanks for reporting! Feel free to reopen or file a new ticket should the issue still persist.
