### ISSUE TITLE
java.lang.NoSuchFieldError: No field Companion of type Lokhttp3/HttpUrl$Companion

### ISSUE THREAD

**Issue by ir2pid** [plaid/plaid-link-android#146]
I get the below error when starting the plaid sdk. The webview loads but the entire app crashes soon after I see the plaid loading screen.

```
2021-03-24 15:44:05.705 27631-27631/com.xx.yy E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.xx.yy, PID: 27631
    java.lang.NoSuchFieldError: No field Companion of type Lokhttp3/HttpUrl$Companion; in class Lokhttp3/HttpUrl; or its superclasses (declaration of 'okhttp3.HttpUrl' appears in /data/app/~~EHIYXy8d39jvFJ3P1QguSA==/com.xx.yy-y_jmuBUyvHI2AMeho8lOHw==/base.apk!classes9.dex)
        at com.plaid.internal.ax0.b(SourceFile:1)
        at com.plaid.internal.ax0.a(SourceFile:6)
        at com.plaid.internal.vq0.a(SourceFile:1)
        at com.plaid.internal.jx0.shouldOverrideUrlLoading(SourceFile:2)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(chromium-TrichromeWebViewGoogle6432.aab-stable-438910534:14)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loop(Looper.java:206)
        at android.app.ActivityThread.main(ActivityThread.java:8419)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by ir2pid** [comment]
This was caused due to other plugins using different versions of okhttp. 

The okhttp versions ranged between `3.1.1, 3.10.0, 3.12.0, 4.0.0` in the dependency graph.

resolved using below resolution strategy in app modules build.gradle

```

configurations.all {
  resolutionStrategy.eachDependency { details ->
    if (details.requested.group == 'com.squareup.okhttp3') {
      details.useVersion "4.0.0"
    }
  }
}


```

**Comment by JeroenMols** [comment]
Great to hear that you managed to resolve this! 💪
