### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.plaid.internal.LinkRedirectActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.

### ISSUE THREAD

**Issue by ir2pid** [plaid/plaid-link-android#148]
This crash happens once I use an oAuth and click on the grant access link.

```
    --------- beginning of crash
2021-03-25 15:46:45.052 9222-9222/com.my.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.my.app, PID: 9222
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.app/com.plaid.internal.LinkRedirectActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3763)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2278)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8419)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:843)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:806)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:693)
        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:170)
        at com.plaid.internal.LinkRedirectActivity.onCreate(SourceFile:2)
        at android.app.Activity.performCreate(Activity.java:8171)
        at android.app.Activity.performCreate(Activity.java:8155)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3736)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3939) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2278) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:246) 
        at android.app.ActivityThread.main(ActivityThread.java:8419) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

**Comment by amytang0** [comment]
Thank you for the crash report, we're looking into reproing now

**Comment by ir2pid** [comment]
A lot of refactoring had to be made but this is fixed when I replace my extended Activity with AppCompatActivity.

**Comment by ir2pid** [comment]
this is resolved by adding to manifest.xml

`<activity android:label="LinkRedirectActivity" android:name="com.plaid.internal.LinkRedirectActivity" android:theme="@style/Theme.AppCompat"></activity>`

**Comment by sezer** [comment]
@ir2pid I know this topic is old but we're getting the same error again. When I add that config to manfiest.xml, I'm getting it is also present at [com.plaid.link:sdk-core:3.10.0].

Any idea about this problem?

**Comment by btrautmann** [comment]
@sezer we had no issue with the above approach. The issue here is that the plaid sdk is declaring this `Activity` as having a `theme` that does not inherit from an `AppCompat` variant. When building an Android application, the manifests declared in the app module and each library will be merged together, and that is your opportunity to override what's declared in the library manifest. When collisions occur (i.e if you and a library are trying to set data for the same element within the manifest), you must indicate that you want your version/setting to override the libraries. That's what the `tools:replace` syntax does below:

```xml
  <activity
       android:name="com.plaid.internal.LinkRedirectActivity"
       android:theme="@style/Theme.AppCompat"
       tools:replace="android:theme"
       />
```

We're saying: "For the `LinkRedirectActivity`, use this (`Theme.AppCompat`) theme. If that `Activity` declares a different theme, override it with ours. This is just a workaround, it should really be fixed as part of the library itself.

**Comment by btrautmann** [comment]
It's worth noting that `lint` or your build itself may complain, saying that it can't resolve the `LinkRedirectActivity`. This will require you to add the plaid sdk to the `compileOnly` configuration for your app module:

`android/app/build.gradle`
```groovy
compileOnly("com.plaid.link:sdk-core:<version>")
```
