### ISSUE TITLE
Update to Protobuf?

### ISSUE THREAD

**Issue by roarapps** [plaid/plaid-link-android#176]
When we upgraded Plaid Link SDK from 3.3.1 to 3.4.0 and we get the following crash in our logs -

 java.lang.ArrayIndexOutOfBoundsException: length=4; index=4
        at com.google.protobuf.MessageSchema.newSchemaForRawMessageInfo(MessageSchema.java:507)
        at com.google.protobuf.MessageSchema.newSchema(MessageSchema.java:227)
        at com.google.protobuf.ManifestSchemaFactory.newSchema(ManifestSchemaFactory.java:77)
        at com.google.protobuf.ManifestSchemaFactory.createSchema(ManifestSchemaFactory.java:71)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:90)
        at com.google.protobuf.Protobuf.schemaFor(Protobuf.java:104)
        at com.google.protobuf.GeneratedMessageLite.makeImmutable(GeneratedMessageLite.java:175)
        at com.google.protobuf.GeneratedMessageLite$Builder.buildPartial(GeneratedMessageLite.java:397)
        at com.google.protobuf.GeneratedMessageLite$Builder.build(GeneratedMessageLite.java:405)
        at com.google.firebase.perf.v1.ApplicationInfo$Builder.setAndroidAppInfo(ApplicationInfo.java:934)
        at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.syncInit(FirebasePerfClearcutLogger.java:278)
        at com.google.firebase.perf.internal.FirebasePerfClearcutLogger.access$000(FirebasePerfClearcutLogger.java:62)
        at com.google.firebase.perf.internal.FirebasePerfClearcutLogger$1.run(FirebasePerfClearcutLogger.java:169)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

Is this anything you've come across? Potentially a library conflict?

**Comment by amytang0** [comment]
Yes, certain versions of the firebase-perf library conflict with the `protobuf-lite` library. Which version of the firebase-perf library are you using?

**Comment by roarapps** [comment]
Hey Amy,

We are on implementation 'com.google.firebase:firebase-perf:19.0.9' (we are on an older version due to another conflict elsewhere)

**Comment by JeroenMols** [comment]
Looking at the `pom.xml` of firebase-perf `19.0.9` I see that it already relies on `protobuf-javalite`
https://maven.google.com/web/index.html#com.google.firebase:firebase-perf:19.0.9

Only the version Firebase uses (3.11.0) is quite a bit older than Link's version (3.17.3).
I'm wondering whether this crash could be cause by firebase not being compatible with `protobuf-javalite` version `3.17.3`?

It also seems like the latest `firebase-perf` library has updated to `protobuf-javalite` version `3.14.0`.

Would you mind checking the firebase issue tracker and file an issue with them?
This doesn't look like a Link SDK crash.

**Comment by roarapps** [comment]
Hi @JeroenMols 

This issue is a crash by Plaid, if we keep plaid at 3.3.1, everything is okay.

As soon as we update to Plaid 3.4.0 we get the crash.

We are not updating any other library.

**Comment by JeroenMols** [comment]
What seems to be happening here is that both `Link` and `firebase-perf` use `protobuf-javalite` as a transitive dependency :

- `Link` requires version `3.17.3`
-  `firebase-perf` requires version `3.11.0`

When building your application, Gradle tries to satisfy both requirements and choses to use the higher version of `protobuf-javalite` `3.17.3`. 

This in turn causes a crash in the `firebase-perf` SDK as shown by the crash stacktrace above. (notice how Plaids namespace `com.plaid.link` isn't part of the stacktrace)

Our recommendation would be to update to a version of `firebase-perf` that is compatible with the latest `protobuf-javalite` version.

Hope this clarifies things, happy to help if anything is still unclear.

**Comment by roarapps** [comment]
Yup understood, theres another conflict with another library which is why we couldn't update firebase pref, will take another look.

Closing as resolved
