### ISSUE TITLE
Crash when opening LinkActivity

### ISSUE THREAD

**Issue by jonandersen** [plaid/plaid-link-android#18]
Version: 0.3.2
Stack trace: 
```
2020-01-16 10:56:15.148 30727-30727/com.public.app.development E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.public.app.development, PID: 30727
    java.lang.RuntimeException: Unable to resume activity {com.public.app.development/com.plaid.link.LinkActivity}: java.io.IOException: javax.crypto.IllegalBlockSizeException
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4205)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.io.IOException: javax.crypto.IllegalBlockSizeException
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:133)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:202)
        at com.plaid.storage.PlaidKeystore.rsaDecrypt(PlaidKeystore.kt:255)
        at com.plaid.storage.PlaidKeystore.getSecretKey(PlaidKeystore.kt:289)
        at com.plaid.storage.PlaidKeystore.encrypt$storage_release(PlaidKeystore.kt:95)
        at com.plaid.storage.PlaidSecureStorage.saveData(PlaidSecureStorage.kt:74)
        at com.plaid.analytics.PlaidAnalyticsImpl.loadIdentity(PlaidAnalyticsImpl.kt:158)
        at com.plaid.analytics.PlaidAnalyticsImpl.getUserId(PlaidAnalyticsImpl.kt:45)
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:90)
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:81)
        at com.plaid.link.LinkActivity.onResume(LinkActivity.kt:81)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
        at android.app.Activity.performResume(Activity.java:7962)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: javax.crypto.IllegalBlockSizeException
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:519)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:531)
        at javax.crypto.Cipher.doFinal(Cipher.java:2002)
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:130)
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:202) 
        at com.plaid.storage.PlaidKeystore.rsaDecrypt(PlaidKeystore.kt:255) 
        at com.plaid.storage.PlaidKeystore.getSecretKey(PlaidKeystore.kt:289) 
        at com.plaid.storage.PlaidKeystore.encrypt$storage_release(PlaidKeystore.kt:95) 
        at com.plaid.storage.PlaidSecureStorage.saveData(PlaidSecureStorage.kt:74) 
        at com.plaid.analytics.PlaidAnalyticsImpl.loadIdentity(PlaidAnalyticsImpl.kt:158) 
        at com.plaid.analytics.PlaidAnalyticsImpl.getUserId(PlaidAnalyticsImpl.kt:45) 
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:90) 
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:81) 
        at com.plaid.link.LinkActivity.onResume(LinkActivity.kt:81) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453) 
        at android.app.Activity.performResume(Activity.java:7962) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
     Caused by: android.security.KeyStoreException: Unknown error
        at android.security.KeyStore.getKeyStoreException(KeyStore.java:1292)
        at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
        at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:531) 
        at javax.crypto.Cipher.doFinal(Cipher.java:2002) 
        at javax.crypto.CipherInputStream.getMoreData(CipherInputStream.java:130) 
        at javax.crypto.CipherInputStream.read(CipherInputStream.java:202) 
        at com.plaid.storage.PlaidKeystore.rsaDecrypt(PlaidKeystore.kt:255) 
        at com.plaid.storage.PlaidKeystore.getSecretKey(PlaidKeystore.kt:289) 
        at com.plaid.storage.PlaidKeystore.encrypt$storage_release(PlaidKeystore.kt:95) 
        at com.plaid.storage.PlaidSecureStorage.saveData(PlaidSecureStorage.kt:74) 
        at com.plaid.analytics.PlaidAnalyticsImpl.loadIdentity(PlaidAnalyticsImpl.kt:158) 
        at com.plaid.analytics.PlaidAnalyticsImpl.getUserId(PlaidAnalyticsImpl.kt:45) 
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:90) 
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:81) 
        at com.plaid.link.LinkActivity.onResume(LinkActivity.kt:81) 
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453) 
        at android.app.Activity.performResume(Activity.java:7962) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
```

**Comment by jonandersen** [comment]
This goes away after removing the app and then installing it again.

**Comment by zsweigart** [comment]
Thanks for the report, we'll look into it.  Are there any steps to reproduce consistently?

**Comment by zsweigart** [comment]
Hi @jonandersen can you try again with version 0.3.3 ? also any other steps would be greatly appreciated

**Comment by zsweigart** [comment]
Hi @jonandersen have you had any luck with 0.3.3 or 0.3.4?

**Comment by jonandersen** [comment]
@zsweigart I'm currently not using plaid link just the old web view approach. Once I get time to test it again in the future I'll let you know

**Comment by zsweigart** [comment]
Thanks, feel free to reopen if the issue persists
