### ISSUE TITLE
upgraded to 0.3.3, LinkActivity not working

### ISSUE THREAD

**Issue by shaurya947** [plaid/plaid-link-android#22]
We were on 0.3.1 and just tried upgrading to 0.3.3. On 0.3.3, calling `openLink` just renders a black screen. The logs keep printing these error lines indefinitely:

```
2020-01-20 10:53:48.084 15560-15560/com.cover.android E/Plog$Companion: java.io.FileNotFoundException: /data/user/0/com.cover.android/files/identityInfo (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at com.plaid.storage.PlaidSecureStorage.loadData(PlaidSecureStorage.kt:110)
        at com.plaid.analytics.PlaidAnalyticsImpl.loadIdentity(PlaidAnalyticsImpl.kt:153)
        at com.plaid.analytics.PlaidAnalyticsImpl.getUserId(PlaidAnalyticsImpl.kt:47)
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:92)
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:83)
        at com.plaid.link.LinkActivity.onResume(LinkActivity.kt:78)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1361)
        at android.app.Activity.performResume(Activity.java:7353)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3763)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3828)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3036)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6938)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
...
```

**Comment by hitesh-banknovo** [comment]
I also faced same issue for this version.

**Comment by zsweigart** [comment]
Hi @shaurya947 thanks for the report.  Did you upgrade the sdk and reinstall the same app or did you install from scratch?

**Comment by shaurya947** [comment]
@zsweigart I tried rebuilding, invalidating Android Studio cache, and installing from scratch several times before deciding to open an issue.

**Comment by zsweigart** [comment]
Just pushed a fix in version 0.3.4

**Comment by shaurya947** [comment]
Thank you, will test it out

**Comment by zsweigart** [comment]
Hi @shaurya947 have you run into this issue on the latest versions (0.3.4 or 0.3.5)

**Comment by shaurya947** [comment]
Just verified that issue doesn't occur on 0.3.5. Closing.
