### ISSUE TITLE
Regarding Plaid authentication, the problem of not being able to open the camera

### ISSUE THREAD

**Issue by LuckyPhz** [plaid/plaid-link-android#248]
Hello, when we were doing Plaid identity authentication, we found that when uploading the relevant ID documents of the user, the camera failed to open. The specific error message is as follows (the error message is not displayed every time)：
`getCameraCharacteristics: 
                                                            java.lang.IllegalArgumentException: getCameraCharacteristics:747: Unable to retrieve camera characteristics for unknown device 3: No such file or directory (-2)
                                                            	at android.hardware.camera2.CameraManager.throwAsPublicException(CameraManager.java:1171)
                                                            	at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:500)
                                                            	at vq0.i(chromium-TrichromeWebViewGoogle.apk-stable-447211483:4)
                                                            	at org.chromium.media.VideoCaptureFactory.isLegacyOrDeprecatedDevice(chromium-TrichromeWebViewGoogle.apk-stable-447211483:1)
                                                            	at org.chromium.media.VideoCaptureFactory.getDeviceName(chromium-TrichromeWebViewGoogle.apk-stable-447211483:1)
                                                            Caused by: android.os.ServiceSpecificException: getCameraCharacteristics:747: Unable to retrieve camera characteristics for unknown device 3: No such file or directory (-2) (code 3)
                                                            	at android.os.Parcel.createExceptionOrNull(Parcel.java:2439)
                                                            	at android.os.Parcel.createException(Parcel.java:2409)
                                                            	at android.os.Parcel.readException(Parcel.java:2392)
                                                            	at android.os.Parcel.readException(Parcel.java:2334)
                                                            	at android.hardware.ICameraService$Stub$Proxy.getCameraCharacteristics(ICameraService.java:812)
                                                            	at android.hardware.camera2.CameraManager.getCameraCharacteristics(CameraManager.java:479)
                                                            	at vq0.i(chromium-TrichromeWebViewGoogle.apk-stable-447211483:4) 
                                                            	at org.chromium.media.VideoCaptureFactory.isLegacyOrDeprecatedDevice(chromium-TrichromeWebViewGoogle.apk-stable-447211483:1) 
                                                            	at org.chromium.media.VideoCaptureFactory.getDeviceName(chromium-TrichromeWebViewGoogle.apk-stable-447211483:1) `

The mobile phone model where the problem occurs is: Galaxy A53 5G (Android 13),Moto g play 2021,(android 11)，Google Pixel 3（android12）

**Comment by phoenixy1** [comment]
Hi!

Is this still an issue, and does it happen all the time or only on certain models?
Have you already followed the instructions in https://plaid.com/docs/link/android/#enable-camera-support-identity-verification-only on enabling camera permissions?

**Comment by phoenixy1** [comment]
Closing due to inactivity / lack of info to reproduce

**Comment by synthosomatic** [comment]
I am an end user trying to verify myself through plaid.
Despite the camera explicitly being allowed for the site, and it showing the camera is allowed in site settings in chrome, it cannot access my camera. It either gives a message about permissions, or shows a black camera view.

**Comment by phoenixy1** [comment]
@synthosomatic please contact the company whose app is using plaid that you're trying to use. they can determine if the issue is with their integration, and if necessary, they can escalate the problem to plaid and can share more useful information with us that will allow us to troubleshoot further.
