### ISSUE TITLE
Disk Read violation when running StrictMode with Plaid SDK

### ISSUE THREAD

**Issue by horowitz** [plaid/plaid-link-android#39]
Hello,

Whenever I run my app on StrictMode I get a DiskViolation when starting the Plaid flow
I'll add here the stacktrace
```
StrictMode policy violation; ~duration=37 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.access(BlockGuardOs.java:69)
        at libcore.io.ForwardingOs.access(ForwardingOs.java:73)
        at android.app.ActivityThread$AndroidOs.access(ActivityThread.java:7246)
        at java.io.UnixFileSystem.checkAccess(UnixFileSystem.java:281)
        at java.io.File.exists(File.java:815)
        at com.plaid.storage.PlaidSecureStorage.loadData(PlaidSecureStorage.kt:108)
        at com.plaid.analytics.PlaidAnalyticsImpl.loadIdentity(PlaidAnalyticsImpl.kt:153)
        at com.plaid.analytics.PlaidAnalyticsImpl.getUserId(PlaidAnalyticsImpl.kt:47)
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:92)
        at com.plaid.analytics.PlaidAnalyticsImpl.track(PlaidAnalyticsImpl.kt:83)
        at com.plaid.link.LinkActivity.onResume(LinkActivity.kt:78)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1453)
        at android.app.Activity.performResume(Activity.java:7962)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4195)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4237)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```
Let me know if you need more info

**Comment by zsweigart** [comment]
Hi @horowitz, we have investigated all strict mode violations and they will be patched in the next release in mid-march

**Comment by JeroenMols** [comment]
Hi @horowitz, we've made a new release with the changes described by @zsweigart. 
Can you please upgrade to Link SDK 1.1.0 and let us know if you are still seeing this issue?

**Comment by JeroenMols** [comment]
Closing this issue due to a month of inactivity, should the problem still persist don't hesitate to reopen or file a new issue.
