### ISSUE TITLE
Parameter accountId is null

### ISSUE THREAD

**Issue by SammyO** [plaid/plaid-link-android#48]
When building release versions of the app (ProGuard obfuscation enabled), I'm getting crashes:

```
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method n.h0.d.k.b, parameter accountId
        at com.plaid.linkbase.models.LinkAccount.<init>(Unknown:2)
        at com.plaid.linkbase.models.LinkAccount$Companion.fromResponse(LinkConnectionModels.kt:58)
        at com.plaid.linkbase.internal.LinkUrlParser.parseSuccess(LinkUrlParser.kt:131)
        at com.plaid.linkbase.internal.LinkUrlParser.parseUrlString(LinkUrlParser.kt:57)
        at com.plaid.linkwebview.LinkWebviewPresenter.parseWebviewResponse(LinkWebviewPresenter.kt:44)
        at com.plaid.linkwebview.PlaidWebClient.shouldOverrideUrlLoading(WebViewClients.kt:73)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:16)
        at android.os.MessageQueue.nativePollOnce(MessageQueue.java:-2)
        at android.os.MessageQueue.next(MessageQueue.java:336)
        at android.os.Looper.loop(Looper.java:174)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

I've added the following lines to proguard-rules, but to no avail:
```
-keep public class Plaid { public protected *; }
-keep public class LinkActivity
-keep public class LinkOAuthActivity
-keep public class PlaidAnalytics
-keep public class com.plaid.linkbase.models.* { public protected *; }
-keep public class com.plaid.plog.LogLevel { public protected *; }
-keep public class com.plaid.ribs.android.RibActivity
-keep public class com.plaid.ribs.android.LifecycleActivity
```

Using `'com.plaid.link:sdk-core:0.3.5'`

**Comment by amytang0** [comment]
HI, can you try upgrading to 1.2.1? 1.0+ versions should be more stable than 0.x

**Comment by SammyO** [comment]
Thanks, that seems to have fixed it. 
I was using quite a bit of code that I found somewhere in a tutorial/guide somewhere online, but seems to be very outdated. I feel like I'm going crazy now though, as I can't find it anymore...

**Comment by amytang0** [comment]
Perfect! Please always let us know if anything (feedback, another issue) comes up. We really value you developers using our SDK :)
