### ISSUE TITLE
okhttp library causing fatal crash

### ISSUE THREAD

**Issue by Bhavik-P** [plaid/plaid-link-android#72]
When I add the Plaid SDK to my app, it crashes on launch with the following exception:
```
    java.lang.NoSuchMethodError: No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/[REDACTED]--rUZKSdQB1b31vp8OQYQDA==/base.apk!classes2.dex)
        at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.java:91)
        at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:74)
        at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:43)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:74)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:74)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Initially, I was encountering what this user experienced here: https://github.com/plaid/plaid-link-android/issues/17. I tried his suggested response which allowed my app to load however once I tried to launch PlaidLink, it would cause a crash because `logging-interceptor` was not found. We don't use `okhttp` as a dependency however we have other libraries that use `okhttp` as a sub-dependency. How can I avoid getting this crash and get Android Plaid SDK up and running?

**Project Details**:
Written in Java
minSdkVersion 23
source/target compatibility: 1.8
Android Plaid SDK - 1.4.1

Please let me know if you want me to provide any more details.

**Comment by amytang0** [comment]
Hi Bhavik,

We have a more flexible fix for 2.0 (coming out roughly around June 15) but in the meantime if your OkHttp library is flexible, add these lines
```
implementation “com.squareup.okhttp3:logging-interceptor:4.6.0”
implementation “com.squareup.okhttp3:okhttp:4.6.0”
```

**Comment by Bhavik-P** [comment]
Hi Amy,

I am still facing the same issue after upgrading to the latest version `2.0.0`

```
 java.lang.NoSuchMethodError: No virtual method toString(Z)Ljava/lang/String; in class Lokhttp3/Cookie; or its super classes (declaration of 'okhttp3.Cookie' appears in /data/app/[redacted]-rex4i_5yHkiIFf351cbe1A==/base.apk:classes2.dex)
        at okhttp3.JavaNetCookieJar.saveFromResponse(JavaNetCookieJar.java:45)
        at com.facebook.react.modules.network.ReactCookieJarContainer.saveFromResponse(ReactCookieJarContainer.java:36)
        at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.kt:207)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:85)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by zsweigart** [comment]
Hi @Bhavik-P 
I haven't been able to reproduce this issue. Is there any more information you can provide especially about your build setup:
* Is this issue in all builds or just when obfuscated? 
* Are you including any okhttp3 (or anything that pulls it in transitively like retrofit) in your gradle file directly? If so what version?
* I notice the stack trace has `com.facebook.react.modules.network.ReactCookieJarContainer.saveFromResponse(ReactCookieJarContainer.java:36)` are you including the Android sdk in a React native project?

**Comment by Bhavik-P** [comment]
Hi @zsweigart 

- This issue is happening on all builds. I've tried both debug and release builds.
- We aren't adding okhttp3 directly into our project however we have libraries that have okhttp3 as a dependency.
     - react-native-cookies
     - react-native-localize
- Yes, we are adding the Android SDK into the React Native project. We've been using Plaid Link SDK for iOS and would prefer to not refactor our entire codebase to add the Android SDK.

I added a resolution strategy which seems to have allowed the app to load.
```
configurations.all {
    resolutionStrategy {
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == "com.squareup.okhttp3") {
                details.useVersion "4.6.0"
            }
        }
    }
}
```

**Comment by Bhavik-P** [comment]
I was able to get Plaid Link SDK to work. I just needed to add the resolution strategy I mentioned above. I didn't have to add okhttp3 dependency as part of my project as @amytang0 [mentioned](https://github.com/plaid/plaid-link-android/issues/72#issuecomment-641471512) earlier

**Comment by zsweigart** [comment]
@Bhavik-P Just so you know we have a React Native Library! https://github.com/plaid/react-native-plaid-link-sdk
