### ISSUE TITLE
java.security.GeneralSecurityException: decryption failed [V 2.0.0-rc3]

### ISSUE THREAD

**Issue by hitesh-banknovo** [plaid/plaid-link-android#77]
I am encountering the below error in Plaid.

**My Code**:
```
com.plaid.link.Plaid.initialize(application)
val linkConfiguration: LinkConfiguration = LinkConfiguration
              .Builder()
              .clientName(getString(R.string.app_name))
              .environment(getPlaidEnvironment())
              .publicKey("{dynamic_public_key}")
              .products(listOf(PlaidProduct.AUTH))
              .webhook(webhook_url)
              .token(pubToken) //if present
              .logLevel(if (BuildConfig.DEBUG) com.plaid.link.configuration.LinkLogLevel.VERBOSE else com.plaid.link.configuration.LinkLogLevel.ASSERT)
              .build()

      com.plaid.link.Plaid.openLink(
              activity = this,
              linkConfiguration = linkConfiguration)
```
**Error**:
```
java.security.GeneralSecurityException: decryption failed
        at com.google.crypto.tink.aead.AeadWrapper$WrappedAead.decrypt(AeadWrapper.java:83)
        at com.plaid.internal.x2.a(SourceFile:2)
        at com.plaid.internal.u2.b(SourceFile:35)
        at com.plaid.internal.o.call(SourceFile:3)
        at io.reactivex.internal.operators.observable.ObservableFromCallable.subscribeActual(ObservableFromCallable.java:43)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

java.lang.IllegalStateException: 
        at com.plaid.internal.t4$f.accept(SourceFile:16)
        at io.reactivex.internal.operators.single.SingleDoOnEvent$DoOnEvent.onSuccess(SingleDoOnEvent.java:55)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:81)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7080)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```
I have tried in an emulator as well as the real Samsung s5e device but it didn't work.

**Comment by JeroenMols** [comment]
Hi @hitesh-banknovo , thanks for reporting this issue!

Is this preventing you from opening our SDK and completing an account link flow? Or is this an error you see printed to the console, but everything seems to work?

We have a known issue with our used encryption library that doesn't affect our core SDK functionality and are actively working on improving that. So if it's just a printed warning you can safely ignore that.

**Comment by hitesh-banknovo** [comment]
It is preventing me to open the SDK completely. As soon as the SDK opens the activity, just after the 2-3 seconds, the activity is closed with the above crash.

**Comment by JeroenMols** [comment]
What error code and message in the `onExit` callback of your `PlaidLinkResultHandler`?
https://github.com/plaid/plaid-link-android/blob/834c66082cc5b9d2094ff4c829b427ff8cd5c4c0/app/src/main/java/com/plaid/linksample/MainActivity.kt#L46

Some extra questions for more context:

- Can you clear the app data and reopen the SDK, what error are you getting then?
- What version of our SDK are you using?
- Can you provide a longer `logcat` output?

**Comment by hitesh-banknovo** [comment]
`**onExit**` method I get

` LinkExit(error=LinkError(displayMessage=, errorCode=INVALID_FIELD, errorMessage=android package name must be whitelisted, see https://plaid.com/docs/link/android/#register-app-id, errorType=INVALID_REQUEST), metadata=LinkExitMetadata(linkSessionId=null, institutionName=null, institutionId=null, requestId=null, status=null, exitStatus=null))`

1. I have uninstalled an application and again install the application still, it is crashed with the above logs.
2. As mention in the title, SDK version is  **2.0.0-rc3**
3. I only get the above two crashes logs in my logcat.

**Comment by JeroenMols** [comment]
Have you added your package name to you account on https://plaid.com/ ?
See instructions at https://plaid.com/docs/link/android/#register-app-id

**Comment by hitesh-banknovo** [comment]
Thanks. The Issue resolved after adding package names and updating SDK version 2.0.0.
