### ISSUE TITLE
Crash when upgrading version from 1.2.1 to any above

### ISSUE THREAD

**Issue by mboychenko** [plaid/plaid-link-android#82]
I tried to update sdk version from 1.2.1 to 1.4.1/2.0.0 and after I call Plaid.openLink
it starts loading but in some point crashes. Can you help with this?
Using 1.2.1, everything is ok. 1.3.0, 1.4.1 or 2.0.0 has crashes. I guess it may be related with using publicKey instead of token, for this call I cant use token until backend provide it to me, we are working on this now. But still, using everything same as for 1.2.1 crashing application.

Logs next ->
**For version 1.4.1**

java.lang.NoSuchFieldError: No field Companion of type Lokhttp3/HttpUrl$Companion; in class Lokhttp3/HttpUrl; or its superclasses (declaration of 'okhttp3.HttpUrl' appears in /data/app/com.*hidden*.us-jI-4itljoMLpDtsEX33PQQ==/base.apk!classes4.dex)
        at com.plaid.q7.b(SourceFile:1)
        at com.plaid.q7.a(SourceFile:8)
        at com.plaid.g8.a(SourceFile:5)
        at com.plaid.s8.shouldOverrideUrlLoading(SourceFile:2)
        at tY.a(PG:3)
        at xl.b(PG:81)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:172)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**For version 2.0.0**
java.lang.NoSuchFieldError: No field Companion of type Lokhttp3/HttpUrl$Companion; in class Lokhttp3/HttpUrl; or its superclasses (declaration of 'okhttp3.HttpUrl' appears in /data/app/com.*hidden*.us-J77NOGFG_2-fN6LVoBNGGQ==/base.apk!classes4.dex)
        at com.plaid.internal.r6.b(SourceFile:1)
        at com.plaid.internal.r6.a(SourceFile:7)
        at com.plaid.internal.c4.a(SourceFile:1)
        at com.plaid.internal.n4.shouldOverrideUrlLoading(SourceFile:2)
        at tY.a(PG:3)
        at xl.b(PG:81)
        at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(PG:172)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

Looks like same, but files/lines different

I have tried with different okHttp versions 3.12.6, 3.12.12, 3.14.9 not sure if problem with this, but results are the same.

**Comment by zsweigart** [comment]
Hi @mboychenko In version 1.2.1 we forced OkHttp version 4.4.0 in version 2.0.0 we simply require OkHttp version to be > 4.0.0.  Could you please try upgrading to version 4.0.0?

**Comment by mboychenko** [comment]
Hi, @zsweigart yep, It was required some changes in whole project to update okhttp to 4+ version, but yes it was helpful, crash gone! Thanks
